services:
    tf-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TERRAFORM_VERSION: "1.15.0"
                INSTALL_AZURE_CLI: "YES"
                INSTALL_AWS_CLI: "YES"
        container_name: terraform_env
        volumes:
            - ./terraform/:/terraform/
            - ./azure_terraform/:/azure_terraform/
            - ./scripts/migrate_state.sh:/usr/local/bin/migrate_state.sh:ro
        working_dir: /terraform/

