apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: financeguard
    namespace: argocd
spec:
    generators:
        - matrix:
              generators:
                  - list:
                        elements:
                            - env: dev
                            - env: stage
                            - env: prod
                  - list:
                        elements:
                            - tier: frontend
                              namespace: react
                            - tier: backend
                              namespace: fastapi
    template:
        metadata:
            name: "financeguard-{{env}}-{{tier}}"
        spec:
            project: financeguard
            source:
                repoURL: 'https://github.com/arshappleid/aws-eks-openTel-pci-dss.git'
                targetRevision: stage
                path: helm/financeguard
                helm:
                    valueFiles:
                        
                        - ../../gitops/environments/{{env}}/financeguard/{{tier}}/values.yaml
                        
                        - ../../gitops/environments/{{env}}/financeguard/{{tier}}/image-digest.yaml
            destination:
                
                name: "financeguard-{{env}}-{{tier}}"
                namespace: "{{namespace}}"
            syncPolicy:
                automated:
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=true
