apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: financeguard
  namespace: argocd
spec:
  description: FinanceGuard PCI-DSS Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
