
replicaCount: 2

appName: financeguard-backend
nameOverride: financeguard-backend
fullnameOverride: financeguard-backend
containerName: fastapi-backend

image:
  repository: 866934333672.dkr.ecr.us-east-1.amazonaws.com/prab-eks-backend
  tag: latest

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: ENVIRONMENT
    value: "stage"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector.financeguard.local:4317"
